### ISSUE TITLE
View All Contributions 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-applet-library#5]
As a user, I want to see if an applet is an original or has been compiled using other applets in the library so that I can keep track of the content. 

The goal of this feature is when applets are copied from the original owner in the applet store, the next owner should show this hyperlink. 
* This should be a hyperlinked text that opens an option for the user to export or view. 
* Selecting view should show a table like the below:
![Slack-mindlogger-design-MATTER-Lab.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/48c383b0-ec79-4281-bea3-d1f94803d591)
* Selecting export should export an excel file with the same table 
* If the applet was not copied from another applet in the library then do not show the View All Contributions button 
* Users are able to copy whole activities and items. Each copy a user conducts should be a separate entry in the table that shows the historical version between owners of applets
* If a copied piece of content is deleted, then the entry in the table should be removed 
* if a user adds an activity or item, then an entry should be added to the table

**Comment by jj105** [comment]
backend complete

**Comment by Sshetty2** [comment]
https://github.com/ChildMindInstitute/mindlogger-backend/pull/1033

**Comment by natalia-muzyka** [comment]
[#1000 The 'View All Contributions' link is missing on the applet detail page](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1000)

**Comment by natalia-muzyka** [comment]
Blocked by #49 The applet detail page url isn't specified according to the applet id and the sharing link from the admin panel (applet detail page currently isn't available)

**Comment by natalia-muzyka** [comment]
1) Issues related to this ticket:
[#77 The "View all contributions" button is displayed for the original applet (not copied from another applet in the library)](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/77)
[#79 The historical version between owners isn't displayed in the contributions table](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/79)

2) Selecting export exports an excel file with the same table but different displays, is this displaying acceptable for now? 
https://www.screencast.com/t/vNEEjCvJrPoi

3) Header images are displayed as links, is this displaying acceptable for now? 
https://www.screencast.com/t/8WcwvdoWh

**Comment by WorldImpex** [comment]
2. I think that should be fixed because its hard for the viewer to know what it means 
3. I think that is okay for now 
@natalia-muzyka

**Comment by natalia-muzyka** [comment]
@WorldImpex , please, let me know if these issues can be resolved within this version and should I kick this ticket back or create separate tickets for the next release

1. The changes made by the current owner are replaced for the item instead of adding a new line to the table with a new applet name
https://www.screencast.com/t/r8C5Gwqm
https://www.screencast.com/t/eVX0VYdY

2. The applet version changes for all the contributions to the current version instead of displaying the version in which the changes were made
https://www.screencast.com/t/hojYY6Y784

3. The horizontal scroll is displayed for the big tables
https://www.screencast.com/t/ZcQgdQdF0M

4. The table headers aren't vertically aligned
https://www.screencast.com/t/vjn01orMyLU

Environment
https://library-staging.mindlogger.org/
Win 10 // Chrome 91.0.4472.114
Applets:
A a Nice applet 111
Original applet (1) transferred 4

**Comment by WorldImpex** [comment]
@natalia-muzyka We should try to fix these for this version

**Comment by natalia-muzyka** [comment]
3 new tickets are created:

1. [The changes made by the current owner are replaced for the item instead of adding a new line to the table with a new applet name #92](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/92)
2. [The applet version changes for all the contributions to the current version instead of displaying the version in which the changes were made #93](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/93)
3. [UI/UX Contributions table issues #94](https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-applet-library/94)

**Comment by natalia-muzyka** [comment]
Works as expected. All the issues are fixed.

Checked on: 
Win 10 // Chrome 91.0.4472.124
